POST http://localhost:8080/tours?memberId=1
Content-Type: application/json

{
  "travelPulpose": "쇼핑",
  "hasChild": 0,
  "crowdPreference": 5,
  "preferenceNature": 5,
  "travelDays": 6
}

###
### 로그인
POST http://localhost:8080/members/login
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "abc"
}

### 회원가입
POST http://localhost:8080/members
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "abc",
  "name": "김아름",
  "phone": "010-1111-1111",
  "gender": "남",
  "age": 31,
  "nationality": "USA"
}

### 회원 전체 조회
GET http://localhost:8080/members

###
### test
GET http://localhost:8080





